"use client";

import { useMemo } from "react";
import { Activity, Download, ShieldCheck, TrendingUp } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useStoredHistory } from "@/lib/history";
import { percent } from "@/lib/utils";

const classes = ["Healthy", "AD", "PD", "MS"];

export default function InsightsPage(){
  const items=useStoredHistory();
  const speech=useMemo(()=>items.flatMap(item=>item.prediction?[item.prediction]:[]),[items]);
  const eegItems=useMemo(()=>items.flatMap(item=>item.eegReport?[item.eegReport]:[]),[items]);
  const summary=useMemo(()=>{const total=speech.length;const confidence=total?speech.reduce((sum,p)=>sum+p.confidence_score,0)/total:0;const risk=total?speech.reduce((sum,p)=>sum+p.risk_score,0)/total:0;const distribution=Object.fromEntries(classes.map(label=>[label,speech.filter(p=>p.predicted_class===label).length]));return{total,confidence,risk,distribution};},[speech]);
  const eegSummary=useMemo(()=>{const conditions=["AD","PD","MS"];const means=Object.fromEntries(conditions.map(name=>{const scores=eegItems.map(report=>report.risk_assessment.conditions[name]?.risk_score??0);return [name,scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0];}));return{total:eegItems.length,means};},[eegItems]);
  function exportData(){const blob=new Blob([JSON.stringify(items,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="neurovoice-research-export.json";anchor.click();URL.revokeObjectURL(url);}
  return <AppShell><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><PageHeader title="Research Insights" description="Aggregate analysis of assessments completed in this browser. No patient data is uploaded for this dashboard."/><Button variant="outline" onClick={exportData} disabled={!items.length}><Download className="size-4"/>Export JSON</Button></div>
    <div className="grid gap-5 md:grid-cols-3"><Card><CardContent className="p-6"><div className="flex justify-between"><span className="text-sm font-semibold text-slate-500">Total assessments</span><TrendingUp className="size-5 text-blue-700"/></div><div className="mt-4 text-4xl font-bold">{summary.total}</div><div className="mt-2 text-xs text-slate-500">Voice and biomedical assessments stored locally</div></CardContent></Card><Card><CardContent className="p-6"><div className="flex justify-between"><span className="text-sm font-semibold text-slate-500">Model confidence</span><ShieldCheck className="size-5 text-emerald-700"/></div><div className="mt-4 text-4xl font-bold">{percent(summary.confidence)}</div><div className="mt-3 h-2 rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-700" style={{width:percent(summary.confidence)}}/></div></CardContent></Card><Card><CardContent className="p-6"><div className="flex justify-between"><span className="text-sm font-semibold text-slate-500">Global risk index</span><Activity className="size-5 text-red-700"/></div><div className={`mt-4 text-4xl font-bold ${summary.risk>=.5?"text-red-700":"text-emerald-700"}`}>{summary.total?percent(summary.risk):"No data"}</div><div className="mt-2 text-xs text-slate-500">Mean model risk score</div></CardContent></Card></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><CardContent className="p-6"><h2 className="section-title">Population Risk Distribution</h2><p className="mt-1 text-sm text-slate-500">Predicted classes across completed assessments</p><div className="mt-7 space-y-5">{classes.map((label,index)=>{const count=summary.distribution[label]??0;const value=summary.total?count/summary.total:0;return <div key={label}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{label}</span><span>{percent(value)} ({count})</span></div><div className="h-3 rounded-full bg-slate-200"><div className={`h-full rounded-full ${index===0?"bg-emerald-700":"bg-blue-700"}`} style={{width:percent(value)}}/></div></div>})}</div></CardContent></Card>
      <Card><CardContent className="p-6"><h2 className="section-title">Confidence Benchmarks</h2><p className="mt-1 text-sm text-slate-500">Average confidence by predicted class</p><div className="mt-8 flex h-64 items-end justify-around gap-4 border-b border-slate-300">{classes.map(label=>{const matching=speech.filter(p=>p.predicted_class===label);const average=matching.length?matching.reduce((sum,p)=>sum+p.confidence_score,0)/matching.length:0;return <div key={label} className="flex h-full flex-1 flex-col items-center justify-end"><span className="mb-2 text-xs font-semibold">{matching.length?percent(average):"-"}</span><div className="w-full max-w-14 rounded-t bg-blue-700" style={{height:`${Math.max(average*85,matching.length?4:0)}%`}}/><span className="mt-3 text-xs font-semibold">{label}</span></div>})}</div></CardContent></Card></div>
    {eegSummary.total>0&&<Card className="mt-6"><CardContent className="p-6"><h2 className="section-title">EEG Risk Scores</h2><p className="mt-1 text-sm text-slate-500">Mean independent risk score across {eegSummary.total} EEG assessment{eegSummary.total===1?"":"s"}. These do not sum to 100%.</p><div className="mt-6 space-y-5">{Object.entries(eegSummary.means).map(([name,value])=><div key={name}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{name}</span><span>{percent(value)}</span></div><div className="h-3 rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-700" style={{width:percent(value)}}/></div></div>)}</div></CardContent></Card>}
    <Card className="mt-6"><CardContent className="p-6"><h2 className="section-title">Classifier Risk Trend</h2><p className="mt-1 text-sm text-slate-500">Most recent assessments, newest on the right</p><div className="mt-6 overflow-hidden rounded-lg bg-slate-50 p-4"><svg viewBox="0 0 800 220" className="h-56 w-full" role="img" aria-label="Risk score trend"><line x1="25" y1="190" x2="775" y2="190" stroke="#cbd5e1"/><line x1="25" y1="30" x2="25" y2="190" stroke="#cbd5e1"/>{items.filter(item=>item.prediction).slice(0,10).reverse().map((item,index,array)=>{const x=40+index*(720/Math.max(array.length-1,1));const y=190-(item.prediction?.risk_score??0)*150;const previous=index?{x:40+(index-1)*(720/Math.max(array.length-1,1)),y:190-(array[index-1].prediction?.risk_score??0)*150}:null;return <g key={item.id}>{previous&&<line x1={previous.x} y1={previous.y} x2={x} y2={y} stroke="#0755d9" strokeWidth="4"/>}<circle cx={x} cy={y} r="6" fill="white" stroke="#0755d9" strokeWidth="3"/></g>})}</svg>{!speech.length&&<p className="-mt-32 mb-24 text-center text-sm text-slate-500">Complete a voice or biomedical assessment to display a trend.</p>}</div></CardContent></Card>
  </AppShell>;
}
